### ISSUE TITLE
Stakeholder communication

### ISSUE THREAD

**Issue by hopkind4** [Mozdzem1/CollabProjTeam4#2]
- describe the feedback you have received from the stakeholder and what features you have rejected and why

**Comment by Mozdzem1** [comment]
Do a head count for the amount of students signed up for an event
Provide information on what events students have signed up, and provide information as to what events students are interested in
Keep student-profiles private
Do not include phone number as an attribute of student profiles
Generate a list for each event viewable by the organizations only, containing information about who has signed up for their event, and what their respective email is.
Provide information about volunteers skill sets
