### ISSUE TITLE
Legal Issues 

### ISSUE THREAD

**Issue by hopkind4** [Mozdzem1/CollabProjTeam4#3]
– Specify which laws will impact the implementation or use of the system

**Comment by Mozdzem1** [comment]
One legal issue we will have is to make sure that Re-SERVD is ADA compliant. This will address the Americans with Disabilities Act. This means that we have to make sure the website is able to be used by people with disabilities and to make sure that people with disabilities are not excluded from participating in any of the events offered on Re-SERVD.
